use_data(Human_HPA_annots,
         Human_subannots,
         Human_traffic_subannots, 
         Human_annots, 
         Human_traffic_annots, 
         Mouse_subannots,
         Mouse_traffic_subannots, 
         Mouse_annots, 
         Mouse_traffic_annots,
         Rat_subannots,
         Rat_traffic_subannots, 
         Rat_annots, 
         Rat_traffic_annots,
         Xenopus_subannots,
         Xenopus_traffic_subannots, 
         Xenopus_annots, 
         Xenopus_traffic_annots,
         Yeast_subannots,
         Yeast_traffic_subannots, 
         Yeast_annots, 
         Yeast_traffic_annots,
         internal = T,
         overwrite = T)
